/**
 * Generate a fresh Stellar keypair for an agent wallet.
 *
 * Usage:
 *   npx tsx scripts/generate-keypair.ts           # write to ./.env (fails if exists)
 *   npx tsx scripts/generate-keypair.ts --out foo.env
 *   npx tsx scripts/generate-keypair.ts --force   # overwrite existing .env
 *
 * The generated secret is NEVER printed to the terminal. It is written
 * directly to a local .env file with mode 600 so it can only be read by
 * the current user. The terminal only sees the public key.
 *
 * Why: STELLAR_SECRET is a wallet private key. Printing it in a terminal
 * exposes it to anyone scrolling back, screen-sharing, or reading terminal
 * history. Writing it straight to a file avoids that entire class of leak.
 */

import { Keypair } from "@stellar/stellar-sdk";
import * as fs from "node:fs";
import * as path from "node:path";

function parseArgs() {
  const argv = process.argv.slice(2);
  let out = ".env";
  let force = false;
  for (let i = 0; i < argv.length; i++) {
    if (argv[i] === "--out") out = argv[++i];
    else if (argv[i] === "--force" || argv[i] === "-f") force = true;
  }
  return { out, force };
}

function main() {
  const { out, force } = parseArgs();
  const outPath = path.resolve(process.cwd(), out);

  if (fs.existsSync(outPath) && !force) {
    console.error(
      `❌ ${out} already exists. Refusing to overwrite without --force.`,
    );
    console.error(
      `   If you want a fresh keypair in a different file:`,
    );
    console.error(
      `     npx tsx scripts/generate-keypair.ts --out .env.new`,
    );
    process.exit(1);
  }

  const kp = Keypair.random();
  const pubkey = kp.publicKey();
  const secret = kp.secret();

  // Build the .env body. We merge into an existing file if --force was
  // passed; otherwise we write a fresh one.
  let body: string;
  if (force && fs.existsSync(outPath)) {
    const existing = fs.readFileSync(outPath, "utf8");
    if (/^STELLAR_SECRET=/m.test(existing)) {
      body = existing.replace(/^STELLAR_SECRET=.*/m, `STELLAR_SECRET=${secret}`);
    } else {
      body = existing.replace(/\n?$/, `\nSTELLAR_SECRET=${secret}\n`);
    }
  } else {
    body = [
      "# Generated by scripts/generate-keypair.ts — do not commit.",
      `STELLAR_SECRET=${secret}`,
      "",
    ].join("\n");
  }

  // Write with mode 600 (owner read/write only). writeFileSync does not
  // atomically set mode on all platforms, so we open-create-chmod.
  const fd = fs.openSync(outPath, "w", 0o600);
  try {
    fs.writeSync(fd, body);
  } finally {
    fs.closeSync(fd);
  }
  // Secret string goes out of scope after this function returns.

  console.log("✅ Stellar keypair generated.");
  console.log(`   Public key:    ${pubkey}`);
  console.log(`   Secret stored: ${outPath}  (mode 600)`);
  console.log("");
  console.log("The secret was NOT printed — read it from the file above if you");
  console.log("need to copy it, and delete the file when you're done.");
  console.log("");
  console.log("Next steps:");
  console.log(`  1. (testnet only) Fund the account:`);
  console.log(`     curl 'https://friendbot.stellar.org?addr=${pubkey}'`);
  console.log(`  2. Load the .env and try it:`);
  console.log(`     npx tsx commands/check-balance/run.ts ${pubkey}`);
}

main();
